apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lhw-openproject-prod

resources:
  - ../../base

labels:
  - pairs:
      environment: production

patches:
  # 1. Database Storage Patch
  - patch: |-
      - op: replace
        path: /spec/volume/storageClass
        value: gp2
      - op: replace
        path: /spec/volume/storage
        value: 10Gi
    target:
      kind: postgresql
      name: lhw-openproject-database

  # 2. Backup PVC Patch
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
      - op: add
        path: /spec/storageClassName
        value: gp2
    target:
      kind: PersistentVolumeClaim
      name: lhw-openproject-postgres-backup

  # 3. Vault & ServiceAccount Patch (Combined)
  - patch: |-
      - op: add
        path: /spec/serviceAccountName
        value: openproject-db-sa
      - op: add
        path: /spec/podAnnotations
        value:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "poc-role"
          vault.hashicorp.com/agent-inject-secret-db: "secret/data/poc/db"
    target:
      kind: postgresql
      name: lhw-openproject-database
