apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lhw-openproject-prod

resources:
  - ../../base

labels:
  - pairs:
      environment: production

patches:
  # Set replicas for production environment
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: poc-memcached
  # Vault POD_INJECTION annotations for runtime secret injection
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: poc-memcached
      spec:
        template:
          metadata:
            annotations:
              vault.hashicorp.com/agent-inject: "true"
              vault.hashicorp.com/role: "poc-role"
              vault.hashicorp.com/service: "http://vault.vault.svc:8200"
              vault.hashicorp.com/agent-inject-secret-db: "secret/data/poc/db"
              vault.hashicorp.com/agent-inject-template-db: |
                {{- with secret "secret/data/poc/db" -}}
                export DB_PASSWORD="{{ .Data.data.password }}"
                export DB_USERNAME="{{ .Data.data.username }}"
                {{- end }}
