apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered/openproject.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: openproject-poc
