apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-rendered/postgres.yaml
  - helm-rendered/postgres-backup-pvc.yaml
  - helm-rendered/postgres-backup-cronjob.yaml
  - helm-rendered/serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: openproject-poc
